### ISSUE TITLE
Tabpanel 选中按钮 的底部的线，宽度不适应

### ISSUE THREAD

**Issue by qunqunyang** [jwfe/tvirus#4]
- [ ] tab选中项底部宽度不适应。
![image](https://user-images.githubusercontent.com/13448746/62043940-4fe59400-b234-11e9-83fc-5e8049d09a37.png)

期望：
![image](https://user-images.githubusercontent.com/13448746/62043987-71468000-b234-11e9-9f1b-e3def8b80607.png)

**Comment by Johnqing** [comment]
已修复
